version: "3.8"

services:w
  web:
    build: ./load_balancer
    environment:
      - SERVER_ID=1
  server:
    container_name: server
    build: server/
    image: server:latest
    ports:
      - "4000:4000"
    networks:
      - app-network
  load_balancer:
    container_name: load_balancer
    build: load_balancer/
    image: load_balancer:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

    

  server:
   image: server:latest
   deploy:
      replicas: 2
   networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
