version: '3.8'

services:
  web:
    build: ./load_balancer
    environment:
      - SERVER_ID=1
    ports:
      - "5000:5000"
    networks:
      - app-network

  server:
   image: server:latest
   deploy:
      replicas: 2
   networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
